### ISSUE TITLE
Rilis v0.2.0

### ISSUE THREAD

**Issue by noaione** [naoTimesdev/webpanel#30]
Fitur baru:
- [x] Menambah/menghapus admin (#10) [PR #24]
- [ ] Menghapus server dari Showtimes (#12) [PR Soon]
- [x] Menambah/Menghapus Alias untuk Proyek (#14) [PR #31]
- [ ] Perbaiki masalah CSRF (#22), ini bisa jadi di delay ke versi lain.

Tasks:
- [ ] Selesaikan 3 fitur baru utama
- [ ] Bump versi

Branch https://github.com/naoTimesdev/webpanel/tree/v0.2.x
